### ISSUE TITLE
No data after logging in

### ISSUE THREAD

**Issue by vanillanesquik** [xinluh/personal_capital_api#1]
Hey,
I am interested in trying out this code since I would like to pull transactions from personal capital.

I installed and ran the login and go the 2-fa prompt and I entered my code.

When to run accounts and transactions samples code I am not getting any data back. Adjusted to transaction periods where I know there should be some existing.

Any thoughts? Does this wrapper still work or has something changed n the site?

Thanks

**Comment by xinluh** [comment]
It is still working for me. Was there any error messages? Are you sure you are signed on to the right account?

**Comment by vanillanesquik** [comment]
Yes, I have transactions within that account. I get the 2fa on my phone. When I run either command it just finishes with no errors and nothing is returned.

**Comment by vanillanesquik** [comment]
I think I have it working now. I was expecting a printed response after running the get accounts/transactions commands. When I set a variable equal and printed the variable I got the output.
