### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by andrewjlaird** [xinluh/personal_capital_api#2]
I’m trying to get personal capital / empower to work on windows.

Has this code worked on windows or just on Linux?

Whenever I try to make the call to login() I get a 400 error back.

**Comment by xinluh** [comment]
@andrewjlaird I don't have a Windows environment to test but https://github.com/xinluh/personal_capital_api/commit/ae8f4e7959e0ef5340224c2e4de7ca44c3c82279 is likely to fix the Windows problem.
